# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
run-name: "Deploy: ${{ github.event.head_commit.message }}"

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "**.html"
      - "**.liquid"
      - ".github/workflows/deploy.yaml"
      - "assets/**"
      - "images/**"
      - "public/**"
      - "eleventy.config.m?js"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  encrypt_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm clean-install
      - name: Insert secrets into html
        env:
          HOTELLILAHDEKOODI: ${{ secrets.HOTELLI_LAHDE_KOODI }}
          HOTELLILAPPEEKOODI: ${{ secrets.SOKOS_HOTEL_KOODI }}
          CONCERT_CONTENT_URL: ${{ secrets.CONCERT_CONTENT_URL }}
        run: |
          sed -i -e "s/\$HOTELLILAHDEKOODI/$HOTELLILAHDEKOODI/g" \
                 -e "s/\$HOTELLILAPPEEKOODI/$HOTELLILAPPEEKOODI/g" \
                 -e "s,\$CONCERT_CONTENT_URL,$CONCERT_CONTENT_URL,g" \
                 participant.html
      - name: Build site with 11ty
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: static-site
          path: "_site"
          if-no-files-found: error
          retention-days: 1
          overwrite: true
  upload-site-to-pages:
    needs: encrypt_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: static-site
          path: "."
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: upload-site-to-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
