name: Encrypt Secrets
run-name: Encrypt after ${{ github.event.head_commit.message }}

on:
  push:
    branches: [ main ]
    paths: [ '_participant_raw.html' ]
  workflow_dispatch:

jobs:
  encrypt:
    name: Encrypt and push participant.html
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pagecrypt npm package
        run: npm install -g pagecrypt

      - name: Replace secrets in _participant_raw.html with environment variables
        env:
          HOTELLILAHDEKOODI: ${{ secrets.HOTELLI_LAHDE_KOODI }}
          HOTELLILAPPEEKOODI: ${{ secrets.SOKOS_HOTEL_KOODI }}
          CONCERT_CONTENT_URL: ${{ secrets.CONCERT_CONTENT_URL }}
        run: |
          sed -i -e "s/\$HOTELLILAHDEKOODI/$HOTELLILAHDEKOODI/g" \
                 -e "s/\$HOTELLILAPPEEKOODI/$HOTELLILAPPEEKOODI/g" \
                 -e "s/\$CONCERT_CONTENT_URL/$CONCERT_CONTENT_URL/g" \
                 _participant_raw.html

      - name: Encrypt secrets
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx pagecrypt _participant_raw.html participant.html "$PASSWORD"

      - name: Commit and push encrypted secrets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add participant.html
          git commit -m "workflow: encrypt secrets after ${{ github.event.head_commit.id }}"
          git push origin main
